export enum BusinessStatus {
    PENDING_VERIFICATION = "PENDING_VERIFICATION",
    PENDING_APPROVAL = "PENDING_APPROVAL",
    VERIFIED = "VERIFIED",
    REJECTED = "REJECTED",
    LICENSE_EXPIRED = "LICENSE_EXPIRED",
    SUSPENDED = "SUSPENDED",
    BANNED = "BANNED",
}

export enum BusinessType {
    VENDOR = "VENDOR",
    SUPPLIER = "SUPPLIER",
    ADMIN = "ADMIN",
    CUSTOMER_PHARMACY = "CUSTOMER_PHARMACY",
}

export enum ActionType {
    ACTIVE = "ACTIVE",
    SUSPENDED = "SUSPENDED",
    INACTIVE = "INACTIVE",
    REJECT = "REJECT",
    APPROVE = "APPROVE",
  }