"use client";

import requestClient from '@/lib/requestClient';
import { handleServerErrorMessage } from '@/utils';
import {
    Modal,
    ModalOverlay,
    ModalContent,
    ModalHeader,
    ModalFooter,
    ModalBody,
    ModalCloseButton,
    Button,
  } from '@chakra-ui/react'
import qrcode from '@public/assets/images/QRCode.svg';
import { useState } from 'react';
import OTPInput from 'react-otp-input';
import { toast } from "react-toastify";

const TwoFactorAuth = (
    {isOpen, onClose, onOpenEnable2fa, data, token}: 
    {isOpen: boolean, onClose: () => void; onOpenEnable2fa: () => void, data: string, token: string}
) => {

    const [otp, setOtp] = useState('');
    const [loading, setLoading] = useState<boolean>(false)

    const ENABLE_2FA = async () => {
        if(otp === "" && otp.length < 5) return;
        try {
            const response = await requestClient({token: token}).post(
                "account/2fa/verify",
                {
                    code: otp
                }
            )
            if(response.status === 200){
                onClose()
                onOpenEnable2fa()
                toast.success(response?.data.message)
            }
        } catch (error) {
            setLoading(false);
            const errorMessage = handleServerErrorMessage(error);
            toast.error(errorMessage);
        }
    }
  return (
    <Modal isCentered isOpen={isOpen} onClose={onClose} size={"lg"}>
        <ModalOverlay />
        <ModalContent>
            <ModalHeader>Enable Two-Factor Authentication</ModalHeader>
            <ModalCloseButton />
            <ModalBody>
                <ol className='list-decimal list-outside space-y-4 px-3 enable-2fa'>
                    <li className='text-gray-600'>To enable 2FA, you need to install an authenticator app like Authy, or Google Authenticator.</li>
                    <li className='text-gray-600'>
                        <p className='mb-2'>Scan the QR Code below with your authenticator app.</p>
                        <div
                        dangerouslySetInnerHTML={{ __html: data }}
                        style={{ width: "100%", height: "100%", margin: "0px auto" }}
                        />
                        <p className='text-center text-[15px] mt-2'>Alternatively, you can use the QR Code Key: <span className='font-medium text-gray-800'>3489323SHJ90A</span></p>
                    </li>
                    <li className='text-gray-600'>
                        <span className=''>Enter the OTP generated by the app and click enable.</span>
                        <OTPInput
                            value={otp}
                            onChange={setOtp}
                            numInputs={6}
                            inputType='number'
                            containerStyle={{display:"flex", gap: "12px", justifyContent: "center"}}
                            inputStyle={{width: "55px", height: "55px", padding: "5px", border: "1px solid #EAECF0", borderRadius: "5px", fontSize: "24px", fontWeight: "bold", marginTop: "12px"}}
                            renderInput={(props) => <input {...props} />}
                        />
                    </li>
                </ol>
            </ModalBody>
            <ModalFooter mt={4}>
            <Button variant={"outline"} mr={3} onClick={onClose}>
                Close
            </Button>
            <Button 
            isLoading={loading}
            disabled={loading}
            loadingText={"Submitting"}
            onClick={ENABLE_2FA} 
            colorScheme={"blue"}>
                Enable
            </Button>
            </ModalFooter>
        </ModalContent>
    </Modal>
  )
}

export default TwoFactorAuth