import {
    Modal,
    ModalOverlay,
    ModalContent,
    ModalHeader,
    ModalFooter,
    ModalBody,
    ModalCloseButton,
    Button,
  } from '@chakra-ui/react'
import qrcode from '@public/assets/images/QRCode.svg';
import Image from 'next/image';

const TwoFactorAuth = (
    {isOpen, onClose, onOpenEnable2fa}: 
    {isOpen: boolean, onClose: () => void; onOpenEnable2fa: () => void}
) => {
  return (
    <Modal isCentered isOpen={isOpen} onClose={onClose} size={"lg"}>
        <ModalOverlay />
        <ModalContent>
            <ModalHeader>Enable Two-Factor Authentication</ModalHeader>
            <ModalCloseButton />
            <ModalBody>
                <ol className='list-decimal list-outside space-y-4 px-3'>
                    <li className='text-gray-600'>To enable 2FA, you need to install an authenticator app like Authy, or Google Authenticator.</li>
                    <li className='text-gray-600'>
                        <p className='mb-2'>Scan the QR Code below with your authenticator app.</p>
                        <Image src={qrcode} alt='' className='mx-auto w-32 h-auto'/>
                        <p className='text-center text-[15px] mt-2'>Alternatively, you can use the QR Code Key: <span className='font-medium text-gray-800'>3489323SHJ90A</span></p>
                    </li>
                    <li className='text-gray-600'>Enter the TOTP generated by the app and click enable.</li>
                </ol>
            </ModalBody>
            <ModalFooter mt={4}>
            <Button variant={"outline"} mr={3} onClick={onClose}>
                Close
            </Button>
            <Button 
            onClick={() => {
                onClose()
                onOpenEnable2fa()
            }} 
            colorScheme={"blue"}>
                Enable
            </Button>
            </ModalFooter>
        </ModalContent>
    </Modal>
  )
}

export default TwoFactorAuth